---
title: "Monte Carlo simulacija"
author: "Jure Zloić i Lovre Jerković"
date: "2022-12-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(magrittr)
library(dplyr)
set.seed(1234)
```

```{r}

vjerojatnosti <- read.csv("statistike/p_vjerojatnosti_igraca.csv")
pobjednici <- read.csv("pobjednici.csv")
players <- vjerojatnosti$Player

prvi_igraci <- pobjednici$Igrac1
drugi_igraci <- pobjednici$Igrac2

v <- character(0)
x <- numeric(0)

sets_cnt <- pobjednici$na_koliko_setova_se_igra_mec

for(i in 1:length(pobjednici$SportEventID)) {
  player1 <- prvi_igraci[i]
  player2 <- drugi_igraci[i]
  if(!(player1 %in% players) | !(player2 %in% players)) {
    print("Ne postoji p vjerojatnost igrača")
    v <- c(v, "X")
    x <- c(x, NA)
    next
  }
  p1 <- vjerojatnosti$CIJELI_MEC_p[vjerojatnosti$Player == player1]
  p2 <- vjerojatnosti$CIJELI_MEC_p[vjerojatnosti$Player == player2]
  j <- 1
  pobijedio_prvi <- 0
  while(j<=400){
    montecarlo(p1, p2, sets_cnt[i])
    j <- j + 1
  }
  if(pobijedio_prvi/400 > 0.5) {
    v <- c(v, player1)
    x <- c(x, pobijedio_prvi/400)
  } else {
    v <- c(v, player2)
    x <- c(x, (400-pobijedio_prvi)/400)
  }
}


```


```{r}
sets <- c(0,0)
names(sets) <- c("Home", "Away")

gems <- c(0,0)
names(gems) <- c("Home", "Away")

points <- c(0,0)
names(points) <- c("Home", "Away")

#pobijedio_prvi <- 0

montecarlo <- function(p1, p2, s){ 

n <- 1

sets["Home"] <- 0
sets["Away"] <- 0

  while (sets["Home"]<s & sets["Away"]<s) {
    gems["Home"] <- 0
    gems["Away"] <- 0
    while(gems["Home"]<6 & gems["Away"]<6){
      
      #gameovi dok jedan ne dode do 6
      points["Home"] <- 0
      points["Away"] <- 0
      points_diff <- 0
      
        
      while(points_diff<2 | (points["Home"]<4 & points["Away"]<4)){
        
        if(n == 1){
          outcome <- sample(1:2, 1,prob = c(p1,1-p1))
          ifelse(outcome==1, points["Home"] <- points["Home"] + 1, points["Away"] <- points["Away"] + 1)
          points_diff <- abs(points["Home"]-points["Away"])
        }else{
          outcome <- sample(1:2, 1,prob = c(p2,1-p2))
          ifelse(outcome==2, points["Home"] <- points["Home"] + 1, points["Away"] <- points["Away"] + 1)    
          points_diff <- abs(points["Home"]-points["Away"])
        }
      }
      
      ifelse(points["Home"] > points["Away"], gems["Home"] <- gems["Home"]+1, gems["Away"] <- gems["Away"]+1)
      
      ifelse(n==1, n <- 2, n <- 1)
      
    }
    
    diff <- abs(gems["Home"]-gems["Away"])
    
    #ako je razlika 1, igraj do pobjede, inace gotovo
    
    if(diff == 1){
      
      #jos jedan game
     
      points["Home"] <- 0
      points["Away"] <- 0
      points_diff <- 0
      
      while(points_diff<2 | (points["Home"]<4 & points["Away"]<4)){
        if(n == 1){
          outcome <- sample(1:2, 1,prob = c(p1,1-p1))
          ifelse(outcome==1, points["Home"] <- points["Home"] + 1, points["Away"] <- points["Away"] + 1)
          points_diff <- abs(points["Home"]-points["Away"])
        }else{
          outcome <- sample(1:2, 1,prob = c(p2,1-p2))
          ifelse(outcome==2, points["Home"] <- points["Home"] + 1, points["Away"] <- points["Away"] + 1)    
          points_diff <- abs(points["Home"]-points["Away"])
        }
      }
      
      ifelse(points["Home"] > points["Away"], gems["Home"] <- gems["Home"]+1, gems["Away"] <- gems["Away"]+1)
      
      ifelse(n==1, n <- 2, n <- 1)
      
      
      diff2 <- abs(gems["Home"]-gems["Away"])
    
      if(diff2 == 0){
        #tiebreak
        points["Home"] <- 0
        points["Away"] <- 0
        points_diff <- 0
        first_serve <- 0
        
        while(points_diff<2 | (points["Home"]<7 & points["Away"]<7)){
          if(first_serve==0){
            
            first_serve <- 1
            
            if(n == 1){
              outcome <- sample(1:2, 1,prob = c(p1,1-p1))
              ifelse(outcome==1, points["Home"] <- points["Home"] + 1, points["Away"] <- points["Away"] + 1)
              points_diff <- abs(points["Home"]-points["Away"])
            }else{
              outcome <- sample(1:2, 1,prob = c(p2,1-p2))
              ifelse(outcome==2, points["Home"] <- points["Home"] + 1, points["Away"] <- points["Away"] + 1)    
              points_diff <- abs(points["Home"]-points["Away"])
            }
            
            ifelse(n==1, n <- 2,n <- 1)
          
          }else{
            cnt <- 0
            while(cnt<2 | points_diff<2 | (points["Home"]<7 & points["Away"]<7)){ 
              if(n == 1){
                outcome <- sample(1:2, 1,prob = c(p1,1-p1))
                ifelse(outcome==1, points["Home"] <- points["Home"] + 1, points["Away"] <- points["Away"] + 1)
                points_diff <- abs(points["Home"]-points["Away"])
              }else{
                outcome <- sample(1:2, 1,prob = c(p2,1-p2))
                ifelse(outcome==2, points["Home"] <- points["Home"] + 1, points["Away"] <- points["Away"] + 1)    
                points_diff <- abs(points["Home"]-points["Away"])
              }
              cnt <- cnt+1
            }
            ifelse(n==1, n <- 2,n <- 1)
          }
        }
        ifelse(points["Home"] > points["Away"], gems["Home"] <- gems["Home"]+1, gems["Away"] <- gems["Away"]+1)
      }
    }
    ifelse(gems["Home"]>gems["Away"], sets["Home"] <- sets["Home"]+1, sets["Away"] <- sets["Away"]+1)
  }
  if(sets["Home"] > sets["Away"]){
    pobijedio_prvi <<- pobijedio_prvi+1
  }
}
```


```{r}

s <- sum(v == pobjednici$Pobjednik)
s

```

```{r}

pobjednici$Klasicni_Monte_Carlo_pobjednik <- v
pobjednici$Klasicni_Monte_Carlo_pobjednik_p <- x

write.csv(pobjednici, "pobjednici.csv")

```


